NAME: VPoser_6D
DEVICE: [0]

TRAIN:
  DATASETS: ['AMASS']
  NUM_WORKERS: 11
  BATCH_SIZE: 64
  END_EPOCH: 6000
  OPTIM:
    TYPE: AdamW
    LR: 1e-4

TEST:
  DATASETS: ['AMASS']
  SPLIT: test
  BATCH_SIZE: 32

LOSS:
  LAMBDA_KL: 1.0e-4
  LAMBDA_LATENT: 1.0e-5
