SMPL_PATH: './deps/body_models/smplh/neutral/model.npz'
DATASETS:
  AMASS: './datasets/AMASS'
  HumanML3D: './datasets/HumanML3D'
HANDRAIL: 'assets/handrail/StraightHandRailllNoTex.obj'
CHAIR: 'assets/chair/APezzi1.obj'
CHAIRBALCK: 'assets/chairblack/chairblack_center.obj'
  
