smpl_path: '/home/czk/Desktop/SMPL/SMPLH_NEUTRAL.pkl'
datasets:
  AMASS: './data/AMASS'
  HumanML3D: './data/HumanML'
HANDRAIL: 'assets/handrail/StraightHandRailllNoTex.obj'
CHAIR: 'assets/chair/APezzi1.obj'
CHAIRBALCK: 'assets/chairblack/chairblack_center.obj'