NAME: VPoser_6D
ACCELERATOR: 'gpu'
DEVICE: [0]
TRAINER: vposer_trainer.VPoserTrainer
FOLDER_EXP: "./saved/Vposer"

MODEL:
  num_neurons : 512
  latentD : 32

TRAIN:
  SEED: 100
  NUM_WORKERS: 11
  BATCH_SIZE: 128
  END_EPOCH: 6000
  OPTIM:
    TYPE: AdamW
    ARGS:
      lr: 1e-4
  LR_SCHEDULER:
    TYPE: ReduceLROnPlateau
    ARGS:
      verbose: true
      patience: 5
  keep_extra_loss_terms_until_epoch: 0
  early_stopping:
    monitor: val_loss
    min_delta: 0.0
    patience: 10
    verbose: True
    mode: min

LOSS:
  loss_kl_wt: 0.005
  loss_rec_wt: 4.0
  loss_matrot_wt: 2.0
  loss_jtr_wt: 2.0
