NAME: Trajectory_MDM

model: Trajectory_MDM
normalize: False
text_encoder: 'embedding'

dataset: HumanML3D

denoiser:
  target: libs.models.TransformerEncoder
  params:
    num_heads: 8
    num_layers: 8
    ff_size: 1024
    dropout: 0.2
    latent_dim: 512
    input_size: 198
    output_size: 198

scheduler:
  target: diffusers.DPMSolverMultistepScheduler
  num_inference_timesteps: 30
  guidance_scale: 7.5
  params:
    num_train_timesteps: 1000
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: 'linear'
    prediction_type: 'sample'

train:
  cond_drop_prob: 0.4
  accelerate: 'gpu'
  saved: 'trajectory_diffusion'
  device: [0]
  num_workers: 16
  batch_size: 64
  end_epoch: 6000
  val_frequency: 1
  optimizer:
    target: AdamW
    params:
      lr: 1e-4
      weight_decay: 1e-5
  lr_scheduler:
    target: ReduceLROnPlateau
    params:
      verbose: true
      factor: 0.8
      patience: 250
      eps: 1e-5
  loss:
    diff_loss: 1.0
    # v2v: 0.1
    # j2j: 0.1
    geodesic_loss: 2.0
