NAME: MDM

MODEL:
  NAME: MDM
  joints_num: 22
  CHECKPOINT: './saved/MDM/checkpoints/epoch=15_val_loss=0.52.ckpt'
  TEXT:
    ENCODER: './deps/clip-vit-base-patch16'
    TOKENIZER: './deps/clip-vit-base-patch16'
  VAE:
    NAME: "VPoser"
    CHECKPOINT: "./saved/Vposer/checkpoints/epoch=37.ckpt"
    args:
      num_neurons : 512
      latentD : 32
  DENOISER:
    NAME: "Denoiser"
    sigma_small: True
    predict_xstart: True
    noise_schedule: 'squaredcos_cap_v2'
    timestep_respacing: ''
    num_inference_timesteps: 1000
    args:
      input_size: 32
      hidden_size: 256
      depth: 9
      num_heads: 4
      mlp_ratio: 2.0
      dropout: 0.1
      activation: "gelu"
      learn_sigma: False
  ACTION:
    num_classes: 12
    class_dropout_prob: 0.1

TRAIN:
  ACCELERATOR: 'gpu'
  DEVICE: [0,1]
  FOLDER_EXP: "./saved/MDM"
  DATASET: HumanML3D
  NUM_WORKERS: 12
  BATCH_SIZE: 8
  END_EPOCH: 6000
  OPTIM:
    TYPE: AdamW
    ARGS:
      lr: 1e-4
  LR_SCHEDULER:
    TYPE: ReduceLROnPlateau
    ARGS:
      verbose: true
      factor: 0.5
      patience: 10
      eps: 1e-5
  early_stopping:
    monitor: val_loss
    min_delta: 0.0
    patience: 50
    verbose: True
    mode: min
  guidance_uncodp: 0.2
  METRICS:
    diff_loss: 'diff_loss'
    v2v: 'v2v'
    j2j: 'j2j'
    v2v_local: 'v2v_local'
  LOSS:
    diff_loss: 1.0
    v2v: 0.0
    j2j: 0.1
    v2v_local: 1.0
